// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskFlowAPI.Data;

#nullable disable

namespace TaskFlowAPI.Migrations
{
    [DbContext(typeof(TaskFlowApiContext))]
    [Migration("20260407174046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskFlowAPI.Models.Projeto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("UserProjetoid")
                        .HasColumnType("integer");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("UserProjetoid");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("TaskFlowAPI.Models.Tarefa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prioridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("projeto_idid")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("projeto_idid");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("TaskFlowAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("UserProjetoid")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("UserProjetoid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaskFlowAPI.Models.UserProjeto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.HasKey("id");

                    b.ToTable("UserProjetos");
                });

            modelBuilder.Entity("TaskFlowAPI.Models.Projeto", b =>
                {
                    b.HasOne("TaskFlowAPI.Models.UserProjeto", null)
                        .WithMany("projeto_id")
                        .HasForeignKey("UserProjetoid");
                });

            modelBuilder.Entity("TaskFlowAPI.Models.Tarefa", b =>
                {
                    b.HasOne("TaskFlowAPI.Models.Projeto", "projeto_id")
                        .WithMany()
                        .HasForeignKey("projeto_idid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("projeto_id");
                });

            modelBuilder.Entity("TaskFlowAPI.Models.User", b =>
                {
                    b.HasOne("TaskFlowAPI.Models.UserProjeto", null)
                        .WithMany("user_id")
                        .HasForeignKey("UserProjetoid");
                });

            modelBuilder.Entity("TaskFlowAPI.Models.UserProjeto", b =>
                {
                    b.Navigation("projeto_id");

                    b.Navigation("user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
